export const siteConfig = {
  name: "Catherine Varas",
  title: "AI & Data Engineer",
  description: "AI & Data Engineer with 5+ years of experience designing and implementing scalable data pipelines, cloud infrastructure, software solutions and intelligent automation, along with 2+ years focused on AI systems.",
  siteUrl: "https://catherine-varas.cofoundy.dev",

  // Light theme: purple · blue · white
  colors: {
    bg: "#ffffff",
    bgAlt: "#f6f4ff",
    surface: "rgba(255, 255, 255, 0.72)",
    primary: "#2563eb",
    primaryLight: "#60a5fa",
    accent: "#7c3aed",
    accentLight: "#a78bfa",
    purple: "#a855f7",
    text: "#0f0a2e",
    textMuted: "#55517a",
    gradient: "from-blue-600 via-violet-600 to-purple-500",
  },

  taglines: [
    "Building AI-Powered Solutions",
    "Engineering Scalable Pipelines",
    "Deploying Computer Vision",
    "Migrating Legacy to Cloud",
  ],

  stats: [
    { value: "+5", label: "Years Experience" },
    { value: "6", label: "Cloud Certifications" },
  ],

  // Served from public/ — keep in sync with the root Varas_Catherine_CV.pdf
  cvFile: "/Varas_Catherine_CV.pdf",

  social: {
    email: "catherine.varas.padilla@gmail.com",
    linkedin: "https://www.linkedin.com/in/catherine-varas/",
    github: "https://github.com/CateHey",
  },

  about: {
    eyebrow: "// about",
    heading: "About me",
    pitch: "I'm Catherine, an AI & Data Engineer with more than 5 years of experience. I design and build data pipelines, cloud platforms and AI systems, and I've done it for a bank, a mining company, a research institute, consultancies and startups. I work across the whole stack: data, backend, AI models and the interfaces people use.",
    proof: "Some of what I've built: moving a bank's core records from legacy systems to the cloud; bringing a mining company's operational data into one place for reporting and analytics; AI tools that automate migrations and accounting work for consulting clients; automations and an AI assistant that run daily operations for teams over WhatsApp; and an analysis and simulation platform for a research lab. In every case I learn the business, understand the data and deliver something that works.",
    valueProps: [
      { title: "End to end", text: "Data, backend, AI and the interface your users touch. One accountable owner." },
      { title: "Production-grade", text: "Tests, CI/CD, validation and documentation come standard, not as extras." },
      { title: "Fast to value", text: "A working prototype in days, then we iterate to production together." },
    ],
    availability: "Available for freelance projects.",
    superpower: "Ready to create innovative solutions and use the latest technology to help solve problems.",
  },

  // Services & products — grouped by category. Projects below declare `service: <key>`
  // and are rendered as proof cards under their category. Websites or other
  // delivered work that aren't "projects" go in the same list with their service key.
  services: [
    {
      key: "automation",
      icon: "bolt",
      title: "AI Agents & n8n Automations",
      pitch: "Agentic workflows that run your operations: WhatsApp, email, ERPs, databases and dashboards orchestrated end to end with n8n and LLMs.",
      deliverables: ["Incident intake & classification bots", "ERP ↔ dashboard ↔ WhatsApp sync", "Approval flows, alerts and reports"],
      tags: ["n8n", "LLMs", "WhatsApp API", "Webhooks"],
    },
    {
      key: "rag",
      icon: "chat",
      title: "RAG & LLM Assistants",
      pitch: "Assistants that answer with your own documents and data, never guesses. Retrieval pipelines, evaluation and full query traceability included.",
      deliverables: ["Knowledge-base chat over your docs", "Code & SQL migration copilots", "Semantic search on Azure AI Search"],
      tags: ["RAG", "Azure AI Search", "HuggingFace", "Claude"],
    },
    {
      key: "ai",
      icon: "chip",
      title: "Custom AI Systems",
      pitch: "End-to-end AI products: from the model and the data pipeline to the interface. OCR extraction, AI coaches, conversational analytics, vision.",
      deliverables: ["Document OCR + LLM extraction", "AI coach & conversational products", "Dashboards that answer questions"],
      tags: ["Python", "Azure ML", "Databricks", "Dash/Plotly"],
    },
    {
      key: "erp",
      icon: "grid",
      title: "ERP & Operations Platforms",
      pitch: "Operations systems designed from scratch or configured to your workflow: inventory, orders, dispatch, roles and live dashboards in one place.",
      deliverables: ["Custom-built ERP modules", "Configuration of existing tools", "Centralised data + reporting"],
      tags: ["PostgreSQL", "Node.js", "Streamlit", "Power BI"],
    },
    {
      key: "web",
      icon: "globe",
      compact: true, // smaller work cards for this category
      title: "Web Apps & Landing Pages",
      pitch: "Fast, modern websites and web apps with AI features built in. Designed, developed and deployed, with analytics from day one.",
      deliverables: ["Landing pages & product sites", "Dashboards and internal tools", "Deployed on Vercel or Azure"],
      tags: ["Astro", "React", "Tailwind", "Vercel"],
    },
    {
      key: "data",
      icon: "database",
      title: "Data Platforms & Cloud Migration",
      pitch: "Pipelines, lakehouses and migrations that hold up in production: from legacy mainframes and SQL Server to Azure, Databricks and Snowflake.",
      deliverables: ["Azure Data Factory + Medallion lakehouse", "Spark batch pipelines & validation", "Power BI analytics layer"],
      tags: ["Azure Data Factory", "Databricks", "Spark", "Snowflake"],
    },
  ],

  process: [
    { step: "01", title: "Discovery", text: "A short call to understand your problem, your data and what 'done' looks like." },
    { step: "02", title: "Prototype", text: "A working version in days so you can test it with real inputs before committing." },
    { step: "03", title: "Production", text: "Hardened, deployed, documented and handed over. Support available after launch." },
  ],

  skills: {
    engineering: ["Python", "TypeScript", "JavaScript", "Java", "SQL", "R", "C#", "Bash", "Node.js", "React", "Astro", "Docker", "GraphQL", "REST APIs"],
    ai: ["YOLO", "SAM2", "Neural Networks", "HuggingFace", "RAG", "scikit-learn", "Deep Learning", "Computer Vision", "Agentic AI", "LangChain", "n8n"],
    cloud: ["Azure", "Azure ML", "Azure Functions", "Azure AI Search", "Azure Data Factory", "AWS", "GCP", "HPC", "GPU Streaming"],
    tools: ["Dash/Plotly", "Power BI", "Streamlit", "matplotlib", "Git", "CI/CD"],
    databases: ["Oracle", "SQL Server", "PostgreSQL", "MySQL", "Elasticsearch"],
  },

  experience: [
    {
      company: "Harmony Australasia",
      subtitle: "Mining · Full-time · Hybrid",
      title: "Data Engineer / Business Intelligence Analyst",
      location: "Australia",
      dateRange: "Sep 2026 – Present",
      featured: true,
      highlights: [
        "Integrated data across multiple mining domains and system types, including operational databases, equipment and telemetry systems, production systems, and other enterprise sources, enabling a unified view of mining operations through designed and developed Azure Data Factory pipelines that integrate and consolidate data into a centralised data lake for Power BI analytics and machine learning applications.",
        "Implemented a Medallion Architecture (Bronze, Silver, Gold) to progressively ingest, standardise, validate, and transform raw operational data into trusted analytical datasets, creating a scalable foundation for enterprise reporting, advanced analytics, and machine learning.",
      ],
      tags: ["Azure Data Factory", "Medallion Architecture", "Data Lake", "Power BI", "Machine Learning"],
    },
    {
      company: "NINCA Tech Services",
      subtitle: "Freelance · Hybrid",
      title: "Artificial Intelligence Engineer",
      location: "Remote",
      dateRange: "Mar 2026 – Present",
      featured: true,
      highlights: [
        "Designed and built an agentic automation platform from the ground up, integrating n8n and LLMs to orchestrate end-to-end business processes and synchronise ERP systems, dashboards, and real-time WhatsApp communication for operational teams.",
        "Developed a custom operations management platform from the ground up, combining ERP functionality, workflow automation, centralised data management, and interactive dashboards into a unified system tailored to business operations.",
        "Built an AI-powered analytics platform from the ground up, featuring a conversational interface that answers data questions and dynamically reconfigures visualisations through natural-language requests, leveraging RAG and LLMs with full end-to-end query traceability.",
      ],
      tags: ["n8n", "Agentic AI", "LLMs", "RAG", "WhatsApp API", "Automation"],
    },
    {
      company: "AIBN — University of Queensland",
      subtitle: "Australian Institute for Bioengineering and Nanotechnology",
      title: "Software & Data Engineer",
      location: "Queensland, Australia",
      dateRange: "Mar 2026 – Sep 2026",
      highlights: [
        "Developed an end-to-end data analysis and simulation system for bio-experiments, integrating heterogeneous bioreactor, sample, and metabolomics data and transforming raw experimental data into validated metrics, visual insights, and actionable results across multiple bioreactor platforms.",
        "Built an interactive environment for analysing and simulating fermentation processes, allowing researchers to explore experiments, modify parameters and variables, recalculate results dynamically, compare runs, and test different fermentation scenarios within a single workflow.",
        "Engineered the platform using an AI-assisted development workflow with Claude Code, combining Sonnet and Opus agents with modular architecture, automated testing, data validation, reproducible workflows, and iterative code review — delivering a sophisticated research tool designed for real-world bioprocessing and presented at GBA 2026 in France.",
      ],
      tags: ["Python", "Dash/Plotly", "Simulation", "Data Pipelines", "Claude Code"],
    },
    {
      company: "UQ Queensland Brain Institute",
      subtitle: "Research Experience",
      title: "Research Volunteer — Computer Vision",
      location: "Brisbane, Australia",
      dateRange: "Nov 2025 – Present",
      highlights: [
        "Built a multi-model pipeline (YOLO + SAM2) for automated animal tracking",
        "Engineered chunked GPU streaming and HPC parallel execution for long video processing",
        "Designed a geometric classifier detecting 6 social interaction types from spatial coordinates",
        "Reconstructed neural network architectures from raw checkpoint weights",
      ],
      tags: ["YOLO", "SAM2", "Computer Vision", "HPC", "GPU"],
    },
    {
      company: "One51",
      subtitle: "Data & Analytics Consultancy · On-site",
      title: "Data & AI Engineer",
      location: "Sydney, Australia",
      dateRange: "Jul 2025 – Feb 2026",
      highlights: [
        "Architected and engineered cloud-based AI systems on Azure, integrating Azure Machine Learning, Durable Functions, Azure AI Search, Key Vault and Azure DevOps CI/CD to deliver scalable AI orchestration, HuggingFace model serving, Logic App integrations, and cost-optimised production workflows.",
        "Developed an AI-powered migration platform that combines metadata-driven processing and Retrieval-Augmented Generation (RAG) to automate and accelerate enterprise analytics migrations, including QlikView → Power BI and SQL Server → Snowflake, reducing manual mapping and improving migration consistency and accuracy.",
        "Engineered an AI-driven accounting automation system on Databricks, combining OCR, structured signal normalisation and LLM-based semantic resolution to transform unstructured financial data into analysis-ready datasets and feed downstream calculation engines through automated Databricks Jobs and deployment pipelines.",
        "Built interactive analytics and migration intelligence applications using Streamlit and Python, providing dependency mapping, migration-gap detection, automated scoring, validation, and data-quality assessment across complex analytics environments.",
      ],
      tags: ["Azure ML", "RAG", "Databricks", "HuggingFace", "Streamlit", "Azure DevOps"],
    },
    {
      company: "BBVA",
      subtitle: "One of Latin America's Largest Banks",
      title: "Associate Software & Data Architect",
      location: "Lima, Peru",
      dateRange: "Jul 2024 – Jan 2025",
      highlights: [
        "Led migration of millions of contractual records from IBM Mainframe to cloud infrastructure using Apache Spark",
        "Designed frameworks for data quality, scalability, and compliance with banking regulatory standards",
        "Developed Java backend routines dynamically querying Mainframe or Oracle systems",
        "Managed centralized contracts module exposing data across banking systems",
      ],
      tags: ["Apache Spark", "Java", "Oracle", "IBM Mainframe"],
    },
    {
      company: "BBVA",
      subtitle: "",
      title: "Software Architect",
      location: "Lima, Peru",
      dateRange: "Oct 2022 – Jul 2024",
      highlights: [
        "Engineered scalable batch pipelines using Apache Spark and Java for multi-product Mainframe-to-cloud migration",
        "Developed reusable Spark routines for data transformation, validation, and reconciliation in Parquet format",
        "Automated business-rule validations and anomaly detection across millions of contract records",
        "Deployed and maintained 70+ reusable components (Java backend, Spark batch, database scripts)",
      ],
      tags: ["Spark", "Java", "Parquet", "CI/CD"],
    },
    {
      company: "Vida Software",
      subtitle: "",
      title: "BI & Data Analyst",
      location: "Lima, Peru",
      dateRange: "Jul 2021 – Feb 2022",
      highlights: [
        "Built Big Data pipelines for performance reporting; automated daily processing of 200+ SFTP files",
        "Designed dashboards for inventory and sales forecasting for multinational retail clients",
        "Built integration pipelines between Hasura GraphQL and SQL Server",
      ],
      tags: ["Python", "Power BI", "GraphQL", "Node.js"],
    },
  ],

  // Proof of work. `service` must match a key in `services` above.
  // Add websites or other delivered work here too (e.g. service: "web").
  projects: [
    {
      service: "automation",
      name: "MineOps Dispatch",
      description: "Agentic AI system that automates mining field operations via WhatsApp. An AI agent receives operator reports, classifies incidents, updates the control room database, and sends real-time confirmations — fully autonomous, end to end.",
      github: "https://github.com/CateHey/mining_operations_n8n_automation",
      live: "https://mining-operations-n8n-automation-2d.vercel.app/",
      liveLabel: "Demo based on request",
      hideGithub: true,
      image: "/projects/mineops-dashboard.png",
      tags: ["n8n", "AI Agent", "WhatsApp", "Vercel"],
    },
    {
      service: "rag",
      name: "Databricks RAG Migration Tool",
      description: "AI-powered system that transforms legacy T-SQL into modern Databricks SQL using RAG, LLM reasoning, and deterministic validators for safe, reliable migration.",
      github: "https://github.com/CateHey/rag_databricks_migration_tool",
      live: "https://vercel-app-sooty-ten.vercel.app",
      image: "/projects/databricks-translator.png",
      tags: ["Python", "RAG", "LLM", "Databricks", "Azure", "Azure Foundry"],
    },
    {
      service: "ai",
      name: "Zenda — AI Financial Coach",
      description: "Workplace-benefit app that turns what's left after the bills into a dated roadmap for one real goal: a trip, a car, a home. One payday check-in, and an AI coach running on Claude that explains every number using the user's own data, never guesses. Built and validated at Weekend of Startups with Swyftx, UQIES and UQ Ventures.",
      github: "",
      live: "https://www.zenda.au/",
      liveLabel: "Live site",
      hideGithub: true,
      image: "/projects/zenda.jpg",
      tags: ["Claude", "AI Coach", "Fintech", "Product Design", "Startup"],
    },
    {
      service: "ai",
      name: "Computer Vision Tracking",
      description: "Computer vision pipeline built with neural networks models such as YOLO and SAM2 to track animals movement for Queensland Brain Institute.",
      github: "https://github.com/CateHey/computer-vision-tracking",
      video: "/projects/computer-vision-tracking.mp4",
      tags: ["Python", "YOLOv8", "SAM2", "Computer Vision"],
    },
    {
      service: "web",
      name: "IDEA Bio",
      description: "Website for IDEA Bio, an NCRIS and UQ-funded biofoundry offering synthetic biology services to Australian researchers and businesses: services, a look inside the facility, partners and contact.",
      github: "",
      live: "https://ideabio.org.au/",
      liveLabel: "Visit site",
      hideGithub: true,
      image: "/projects/web-ideabio.jpg",
      tags: ["Corporate Website", "Research", "SEO"],
    },
    {
      service: "web",
      name: "GB Safety Solutions",
      description: "Bilingual website for an occupational health and safety consultancy: services, management systems, audits, training, team and contact.",
      github: "",
      live: "https://gb-solutions-consulting-website.vercel.app/",
      liveLabel: "Visit site",
      hideGithub: true,
      image: "/projects/web-gbsafety.jpg",
      tags: ["Business Website", "Bilingual", "Vercel"],
    },
    {
      service: "web",
      name: "Miluska Buelot — Portfolio",
      description: "Professional portfolio for an industrial engineer and occupational health and safety consultant: profile, experience, services and contact.",
      github: "",
      live: "https://portfolio-miluska-buelot.vercel.app/",
      liveLabel: "Visit site",
      hideGithub: true,
      image: "/projects/web-miluska.jpg",
      tags: ["Portfolio", "Landing Page", "Vercel"],
    },
    {
      service: "data",
      name: "Predictive Maintenance Lakehouse",
      description: "Predictive Maintenance Pipeline for Industrial IoT using lakehouse architecture.",
      github: "https://github.com/CateHey/predictive-maintenance-lakehouse-industrial",
      live: "https://predictive-maintenance-lakehouse-industrial-hi3j0wxd6.vercel.app/",
      image: "/projects/maintenance-dashboard.png",
      tags: ["Jupyter", "IoT", "Machine Learning", "Data Pipeline"],
    },
    {
      service: "data",
      name: "Traffic Analysis Spark HDFS",
      description: "Big data pipeline built with Spark using HDFS files to analyze traffic and identify causes of it in Sydney.",
      github: "https://github.com/CateHey/traffic-analysis-spark-hdfs-pipeline",
      live: "https://traffic-analysis-spark-hdfs-pipelin.vercel.app/",
      image: "/projects/traffic-analysis-spark.png",
      tags: ["Spark", "HDFS", "Docker", "Big Data"],
    },
  ],

  certifications: [
    {
      name: "Fabric Data Engineer Associate",
      code: "DP-700",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Fabric Analytics Engineer Associate",
      code: "DP-600",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Power BI Data Analyst Associate",
      code: "PL-300",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Cloud Practitioner",
      code: "CLF-C02",
      provider: "AWS",
      icon: "aws",
    },
    {
      name: "Azure Fundamentals",
      code: "AZ-900",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Generative AI Fundamentals",
      code: "",
      provider: "Databricks",
      icon: "ai",
    },
  ],

  education: [
    {
      school: "University of Queensland",
      degree: "Master in Data Science",
      dateRange: "2025 – Jun 2026",
      location: "Brisbane, Australia",
      highlights: ["Cloud Computing", "Machine Learning", "AI", "Deep Learning", "Bioinformatics"],
      featured: true,
    },
    {
      school: "University of La Rioja (UNIR)",
      degree: "Master of Artificial Intelligence",
      dateRange: "2024 – 2025",
      location: "Spain",
      highlights: ["Generative AI", "Machine Learning", "Computer Vision", "Neural Networks"],
    },
    {
      school: "Peruvian University of Applied Sciences (UPC)",
      degree: "Bachelor of Industrial Engineering",
      dateRange: "2019 – 2023",
      location: "Lima, Peru",
      highlights: ["Project Management", "Process Optimization"],
    },
    {
      school: "Institute Cibertec",
      degree: "Associate's in Computer Science",
      dateRange: "2019 – 2022",
      location: "Lima, Peru",
      highlights: ["SQL", "Java", "Python", "Web Development"],
    },
  ],
};
