export const siteConfig = {
  name: "Catherine Varas",
  title: "AI & Data Engineer",
  description: "AI & Data Engineer focused on designing and implementing AI systems end to end — from the data infrastructure that feeds the models to the orchestration layers that make them work in production. My experience spans agentic AI and RAG systems for enterprise clients, large-scale cloud migrations, and scalable data architectures across industries.",
  siteUrl: "https://catherine-varas.cofoundy.dev",

  colors: {
    bg: "#030712",
    bgAlt: "#0f172a",
    surface: "#1e293b",
    surfaceLight: "#334155",
    primary: "#3b82f6",
    primaryLight: "#93c5fd",
    accent: "#8b5cf6",
    accentLight: "#c4b5fd",
    text: "#f1f5f9",
    textMuted: "#94a3b8",
    gradient: "from-blue-500 via-violet-500 to-pink-500",
  },

  taglines: [
    "Building AI-Powered Solutions",
    "Engineering Scalable Pipelines",
    "Deploying Computer Vision",
    "Migrating Legacy to Cloud",
  ],

  stats: [
    { value: "+5", label: "Years Experience" },
    { value: "6", label: "Cloud Certifications" },
  ],

  social: {
    email: "catherine.varas.padilla@gmail.com",
    linkedin: "https://www.linkedin.com/in/catherine-varas/",
    github: "https://github.com/CateHey",
  },

  about: {
    intro: "AI & Data Engineer focused on designing and implementing AI systems. I work across the full picture, from the data infrastructure that feeds the models to the orchestration layers that make them work in production. My experience spans computer vision pipelines for scientific research, RAG and automation systems for enterprise clients, and large-scale data architectures across different industries.",
    journey: "Lima, Peru → Brisbane, Australia",
    current: "Having worked across data engineering, software architecture, and applied AI helps me design systems that are robust and actually hold up in production. I bring a research-driven approach to every problem, I learn the domain, understand the data, and deliver solutions that work reliably at scale.",
    superpower: "I'm keen to be part of projects in AI, machine learning, or data architecture, with a team tackling meaningful problems.",
  },

  skills: {
    engineering: ["Python", "R", "Java", "SQL", "Bash", "C#", "JavaScript"],
    ai: ["YOLO", "SAM2", "Neural Networks", "HuggingFace", "RAG", "scikit-learn", "Deep Learning", "Computer Vision", "Agentic AI", "LangChain", "n8n"],
    cloud: ["Azure ML", "Azure Functions", "Azure AI Search", "AWS", "GCP", "HPC", "GPU Streaming"],
    tools: ["Dash/Plotly", "Power BI", "Streamlit", "matplotlib", "Git", "CI/CD"],
    databases: ["Oracle", "SQL Server", "PostgreSQL", "MySQL", "Elasticsearch"],
  },

  experience: [
    {
      company: "AIBN — University of Queensland",
      subtitle: "Australian Institute for Bioengineering and Nanotechnology",
      title: "Software Engineer — Research Data Pipelines",
      location: "Brisbane, Australia",
      dateRange: "Mar 2026 – Present",
      featured: true,
      highlights: [
        "Developed a full-stack data analysis pipeline for fermentation research: volume reconstruction, mass balances, growth rate estimation, and automated phase detection",
        "Built an interactive Dash/Plotly dashboard for researchers to explore data and compare replicates",
        "Documented every formula, assumption, and design decision for reproducibility standards",
      ],
      tags: ["Python", "Dash/Plotly", "Data Analysis", "Machine Learning"],
    },
    {
      company: "UQ Queensland Brain Institute",
      subtitle: "Research Experience",
      title: "Research Volunteer — Computer Vision",
      location: "Brisbane, Australia",
      dateRange: "Nov 2025 – Present",
      highlights: [
        "Built a multi-model pipeline (YOLO + SAM2) for automated animal tracking",
        "Engineered chunked GPU streaming and HPC parallel execution for long video processing",
        "Designed a geometric classifier detecting 6 social interaction types from spatial coordinates",
        "Reconstructed neural network architectures from raw checkpoint weights",
      ],
      tags: ["YOLO", "SAM2", "Computer Vision", "HPC", "GPU"],
    },
    {
      company: "One51",
      subtitle: "Data & Analytics Consultancy",
      title: "Data & AI Consultant",
      location: "Sydney, Australia",
      dateRange: "Jul 2025 – Mar 2026",
      highlights: [
        "Designed AI orchestration workflows using Azure ML, Durable Functions, Azure AI Search, and HuggingFace",
        "Developed AI RAG systems to automate analytics platform migrations",
        "Constructed an AI-based accounting automation pipeline on Databricks integrating OCR and LLM-assisted semantic resolution",
        "Built interactive applications for metadata visualization and dependency tracking",
      ],
      tags: ["Azure ML", "RAG", "Databricks", "HuggingFace"],
    },
    {
      company: "BBVA",
      subtitle: "One of Latin America's Largest Banks",
      title: "Associate Software & Data Architect",
      location: "Lima, Peru",
      dateRange: "Jul 2024 – Jan 2025",
      highlights: [
        "Led migration of millions of contractual records from IBM Mainframe to cloud infrastructure using Apache Spark",
        "Designed frameworks for data quality, scalability, and compliance with banking regulatory standards",
        "Developed Java backend routines dynamically querying Mainframe or Oracle systems",
        "Managed centralized contracts module exposing data across banking systems",
      ],
      tags: ["Apache Spark", "Java", "Oracle", "IBM Mainframe"],
    },
    {
      company: "BBVA",
      subtitle: "",
      title: "Software Architect",
      location: "Lima, Peru",
      dateRange: "Oct 2022 – Jul 2024",
      highlights: [
        "Engineered scalable batch pipelines using Apache Spark and Java for multi-product Mainframe-to-cloud migration",
        "Developed reusable Spark routines for data transformation, validation, and reconciliation in Parquet format",
        "Automated business-rule validations and anomaly detection across millions of contract records",
        "Deployed and maintained 70+ reusable components (Java backend, Spark batch, database scripts)",
      ],
      tags: ["Spark", "Java", "Parquet", "CI/CD"],
    },
    {
      company: "Vida Software",
      subtitle: "",
      title: "BI & Data Analyst",
      location: "Lima, Peru",
      dateRange: "Jul 2021 – Feb 2022",
      highlights: [
        "Built Big Data pipelines for performance reporting; automated daily processing of 200+ SFTP files",
        "Designed dashboards for inventory and sales forecasting for multinational retail clients",
        "Built integration pipelines between Hasura GraphQL and SQL Server",
      ],
      tags: ["Python", "Power BI", "GraphQL", "Node.js"],
    },
  ],

  projects: [
    {
      name: "MineOps Dispatch",
      description: "WhatsApp-to-control-room automation for mining operations. AI agent classifies field reports, updates the operations database, and confirms back to the operator — end to end in under 3 seconds.",
      github: "https://github.com/CateHey/mining_operations_n8n_automation",
      live: "https://mining-operations-n8n-automation-2d.vercel.app/",
      liveLabel: "Demo based on request",
      hideGithub: true,
      image: "/projects/mineops-dashboard.png",
      tags: ["n8n", "AI Agent", "WhatsApp", "Vercel"],
    },
    {
      name: "T-SQL to Databricks LLM + RAG Translator",
      description: "AI-powered engine that transforms legacy T-SQL into modern Databricks SQL using RAG, LLM reasoning, and deterministic validators for safe, reliable migration.",
      github: "https://github.com/CateHey/rag_databricks_migration_tool",
      live: "https://vercel-app-sooty-ten.vercel.app",
      image: "/projects/databricks-translator.png",
      tags: ["Python", "RAG", "LLM", "Databricks"],
    },
    {
      name: "Computer Vision Tracking",
      description: "Computer vision pipeline built with neural networks models such as YOLO and SAM2 to track animals movement for Queensland Brain Institute.",
      github: "https://github.com/CateHey/computer-vision-tracking",
      video: "/projects/computer-vision-tracking.mp4",
      tags: ["Python", "YOLOv8", "SAM2", "Computer Vision"],
    },
    {
      name: "AWS Deployed System",
      description: "Medical system for start-up deployed in AWS cloud services with scalable architecture.",
      github: "https://github.com/CateHey/aws_deployed_system",
      tags: ["Python", "AWS", "Cloud", "Healthcare"],
    },
    {
      name: "Predictive Maintenance Lakehouse",
      description: "Predictive Maintenance Pipeline for Industrial IoT using lakehouse architecture.",
      github: "https://github.com/CateHey/predictive-maintenance-lakehouse-industrial",
      live: "https://predictive-maintenance-lakehouse-industrial-hi3j0wxd6.vercel.app/",
      image: "/projects/maintenance-dashboard.png",
      tags: ["Jupyter", "IoT", "Machine Learning", "Data Pipeline"],
    },
    {
      name: "Traffic Analysis Spark HDFS",
      description: "Big data pipeline built with Spark using HDFS files to analyze traffic and identify causes of it in Sydney.",
      github: "https://github.com/CateHey/traffic-analysis-spark-hdfs-pipeline",
      live: "https://traffic-analysis-spark-hdfs-pipelin.vercel.app/",
      image: "/projects/traffic-analysis-spark.png",
      tags: ["Spark", "HDFS", "Docker", "Big Data"],
    },
  ],

  certifications: [
    {
      name: "Fabric Data Engineer Associate",
      code: "DP-700",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Fabric Analytics Engineer Associate",
      code: "DP-600",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Power BI Data Analyst Associate",
      code: "PL-300",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Cloud Practitioner",
      code: "CLF-C02",
      provider: "AWS",
      icon: "aws",
    },
    {
      name: "Azure Fundamentals",
      code: "AZ-900",
      provider: "Microsoft",
      icon: "microsoft",
    },
    {
      name: "Generative AI Fundamentals",
      code: "",
      provider: "Databricks",
      icon: "ai",
    },
  ],

  education: [
    {
      school: "University of Queensland",
      degree: "Master in Data Science",
      dateRange: "2025 – Jun 2026",
      location: "Brisbane, Australia",
      highlights: ["Cloud Computing", "Machine Learning", "AI", "Deep Learning", "Bioinformatics"],
      featured: true,
    },
    {
      school: "University of La Rioja (UNIR)",
      degree: "Master of Artificial Intelligence",
      dateRange: "2024 – 2025",
      location: "Spain",
      highlights: ["Generative AI", "Machine Learning", "Computer Vision", "Neural Networks"],
    },
    {
      school: "Peruvian University of Applied Sciences (UPC)",
      degree: "Bachelor of Industrial Engineering",
      dateRange: "2019 – 2023",
      location: "Lima, Peru",
      highlights: ["Project Management", "Process Optimization"],
    },
    {
      school: "Institute Cibertec",
      degree: "Associate's in Computer Science",
      dateRange: "2019 – 2022",
      location: "Lima, Peru",
      highlights: ["SQL", "Java", "Python", "Web Development"],
    },
  ],
};
